name: youtube_player_iframe_web_example
description: "An example of how to use the youtube_player_iframe_web plugin."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  youtube_player_iframe: ^5.1.2
  connectivity_plus: ^5.0.2
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true